[package]
name = "rickview"
version = "0.0.5"
edition = "2021"
license = "MIT"
keywords = ["rdf", "semantic-web", "linked-data"]
categories = ["web-programming::http-server"]
description = "A fast RDF viewer (Linked Data browser)"
authors = ["Konrad Höffner"]
readme = "README.md"
repository = "https://github.com/konradhoeffner/rickview"

[dependencies]
sophia = "0.7" 
actix-web = "4"
multimap = "0.8"
tinytemplate = "1"
serde = { version = "1", features = ["derive"] }
config = { version = "0.13", default-features = false, features = ["toml"] }
log = "0.4"
env_logger = { version = "0.9", default-features = false, features = ["termcolor", "atty"], optional = true }
hdt = {version = "0.0.1", optional = true }

[features]
default = ["rdfxml", "log", "hdt"]
rdfxml = ["sophia/xml"] # ~ 300kb binary size increase
log = ["env_logger"] # ~ 500 kb binary size increase
hdt = ["dep:hdt"]

[profile.release]
# see https://fasterthanli.me/articles/why-is-my-rust-build-so-slow
lto = "thin"
strip = true
incremental = true # disable in CI with CARGO_INCREMENTAL=0
