[package]
name = "rickview"
version = "0.1.0"
edition = "2021"

[dependencies]
sophia = "0.7" 
actix-web = "4"
lazy_static = "1.4"
multimap = "0.8"
tinytemplate = "1"
serde = { version = "1", features = ["derive"] }
config = { version = "0.13", default-features = false, features = ["toml"] }
log = "0.4.17"
env_logger = { version = "0.9.0", default-features = false, features = ["termcolor", "atty"], optional = true }

[features]
default = ["rdfxml", "log"]
rdfxml = ["sophia/xml"] # ~ 300kb binary size increase
log = ["env_logger"] # ~ 500 kb binary size increase

[profile.release]
# see https://fasterthanli.me/articles/why-is-my-rust-build-so-slow
lto = "fat"
strip = true
incremental = true # disable in CI with CARGO_INCREMENTAL = 0
