[package]
name = "rickview"
version = "0.1.0"
edition = "2021"

[dependencies]
sophia = "0.7"
actix-web = "4"
lazy_static = "1.4"
multimap = "0.8"
tinytemplate = "1"
serde = { version = "1", features = ["derive"] }
