env:
  NAME: rickview
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -Dwarnings

name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   target: i686-unknown-linux-gnu
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          # - os: windows-latest
          #   target: i686-pc-windows-msvc
          # - os: windows-latest
          #   target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@nightly-2023-02-15
      - run: rustup component add clippy --toolchain nightly-2023-02-15-${{ matrix.target }}
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - name: Install linker
        if: matrix.target == 'i686-unknown-linux-gnu'
        run: sudo apt-get install gcc-multilib
      # - run: cargo check
      # populate cache for release workflow
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target ${{ matrix.target }} --release
      - name: Clippy
        run: cargo clippy --no-deps --all-features --tests --benches -- -Dclippy::all
