name: Lint and Check

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - '.env.dist'
      - '.github/dependabot.yml'
      - '.github/workflows/release.yml'
      - 'Dockerfile'
      - 'LICENSE'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.dockerignore'
      - '.env.dist'
      - '.github/dependabot.yml'
      - '.github/workflows/release.yml'
      - 'Dockerfile'
      - 'LICENSE'
      - 'README.md'

jobs:
  check:
    #strategy:
      #matrix:
        #include:
          #- os: ubuntu-latest
          #- os: macos-latest
          #- os: windows-latest
    #runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          components: rustfmt,clippy
          toolchain: nightly-2024-01-31
      - name: fmt
        run: cargo fmt --check
      - name: clippy
        run: cargo clippy --no-deps --all-features
      - name: check
        run: cargo check
